name: deployment
on: 
 push:
  branches:
    - master
jobs:
 build:
  runs-on: ubuntu-latest
  environment: test
  steps:
   - name: get code
     uses: actions/checkout@v1
   - name: Run Server
     run: npm start on $url
   - name: Output information
     run: echo "Connected"
     
   
     
