name: deployment
on: 
 push:
  branches:
    - master
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - name: connect to mongodb
     uses: actions/checkout@v3
   - name: Start MongoDB
     uses: supercharge/mongodb-github-action@1.8.0  
     
